version: "3.8"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/src/app
    command: npm run start:dev
    ports:
      - "3000:3000"
  db:
    image: mysql:8.0.41
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root_pass'
      MYSQL_USER: 'dev'
      MYSQL_PASS: 'password'
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data: